spring.application.name=lunaris-mail-api

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lunaris.school@gmail.com
spring.mail.password=nhzt icin jtpc wehk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
